apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-skyw-agcam-sim
  name: lvm-skyw-agcam-sim
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - image: localhost/lvm_actor:latest
    name: lvm-skyw-agcam
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /root/lvm
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVM_ACTOR
      value: "lvmcam"
    - name: LVM_ACTOR_CONFIG
      value: "lvm.skyw.agcam"
    - name: LVM_ACTOR_ARGS
      value: "--verbose --simulate"
    - name: LVM_DEBUG
      value: "yes"
    - name: LVM_RMQ_HOST
      value: "192.168.49.2"
  volumes:
  - hostPath:
      path: /lvm
      type: Directory
    name: data-lvm-host-1
  - hostPath:
      path: /lvm/var/data
      type: Directory
    name: data-lvm-host-2

