apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-skye-ag
  name: lvm-skye-ag
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-def
spec:
  terminationGracePeriodSeconds: 0

  volumes:
  - hostPath:
      path: /lvm
      type: Directory
    name: data-lvm-host-1
  - hostPath:
      path: /lvm/var/data
      type: Directory
    name: data-lvm-host-2
  
  containers:
  - name: lvm-skye-agcam
    image: ghcr.io/sdss/lvmactor:latest
    imagePullPolicy: IfNotPresent
#    image: localhost/lvm_actor:latest
#    imagePullPolicy: Never
    volumeMounts:
    - mountPath: /root/lvm
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVM_ACTOR
      value: "lvmcam"
    - name: LVM_CAM_TYPE
      value: "araviscam"
    - name: LVM_ACTOR_CONFIG
      value: "lvm.skye.agcam"
    - name: LVM_ACTOR_ARGS
      value: "--rmq_url=amqp://guest:guest@10.8.38.21:5672/ --verbose"
    - name: LVM_DEBUG
      value: "yes"

  - name: lvm-skye-agp
    image: ghcr.io/sdss/lvmactor:latest
#    image: localhost/lvm_actor:latest
    volumeMounts:
    - mountPath: /root/lvm
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVM_ACTOR
      value: "lvmagp"
    - name: LVM_ACTOR_CONFIG
      value: "lvm.skye.agp"
    - name: LVM_ACTOR_ARGS
      value: "--rmq_url=amqp://guest:guest@10.8.38.21:5672/ --verbose"
    - name: LVM_DEBUG
      value: "yes"
