apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-moe-mpia
  name: lvm-moe-mpia
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - image: ghcr.io/sdss/lvmtan:latest
    name: lvm-moe
    ports:
    - containerPort: 40000
      hostPort: 40000
    - containerPort: 5900
      hostPort: 5905
    - containerPort: 6080
      hostPort: 8095
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /root/lvm
      name: data-lvm-host-1
    env:
    - name: BASDARD_PORT
      value: "40000"
    - name: BASDARD_CONFIG
      value: "lvm/lvm.moe-mpia.conf"
    - name: BASDARD_UI
      value: "lvm/lvm.all.ui"
    - name: VNC_GEOM
      value: "860x900"
    - name: LVM_RMQ
      value: "192.168.49.2"
    - name: LVM_DEBUG
      value: "yes"
  volumes:
  - hostPath:
      path: /lvm
      type: Directory
    name: data-lvm-host-1

