apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-spec-agcam
  name: lvm-spec-agcam
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-def
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: lvm-spec-agcam
    image: ghcr.io/sdss/lvmactor:latest
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /root/lvm
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVM_ACTOR
      value: "lvmcam"
    - name: LVM_ACTOR_CONFIG
      value: "lvm.spec.agcam"
    - name: LVM_DEBUG
      value: "yes"
    - name: LVM_RMQ_HOST
      value: "192.168.49.2"
  volumes:
  - hostPath:
      path: /lvm
      type: Directory
    name: data-lvm-host-1
  - hostPath:
      path: /lvm/var/data
      type: Directory
    name: data-lvm-host-2

