# kubectl create -f to import
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-nps-sim
  name: lvm-nps-sim
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: lvm-nps
    image: ghcr.io/sdss/lvmactor:latest
#    image: localhost/lvm_actor:latest
#    imagePullPolicy: Never
    securityContext:
      capabilities: {}
    volumeMounts:
    - mountPath: /root/lvmnps
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVM_ACTOR
      value: "lvmnps"
    - name: LVM_ACTOR_CONFIG
      value: "lvmnps_dummy"
    - name: LVM_ACTOR_ARGS
      value: "--verbose --rmq_url=amqp://guest:guest@192.168.49.2:5672/"
    - name: LVM_DEBUG
      value: "yes"
    #command: ["/bin/sh"]
    #args: ["-c", "echo $LVMT_NPS_CONFIG; \
                  #NPS_CONF=${LVMT_NPS_CONFIG%.*}_${LVMT_RMQ}.yml; \
                  #sed \"s/host: .*$/host: $LVMT_RMQ/\" < $LVMT_NPS_CONFIG > ${LVMT_NPS_CONFIG%.*}_${LVMT_RMQ}.yml; \
                  #echo $NPS_CONF; \
                  #trap : TERM INT; lvmnps -v -c $NPS_CONF start --debug  & wait"]
  volumes:
  - name: data-lvm-host-1
    hostPath:
      path: /lvm/lvmnps
      type: Directory
  - name: data-lvm-host-2
    hostPath:
      path: /lvm/var/data
      type: Directory

    
