apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-08T14:35:32Z"
  labels:
    app: lvm-sci-ag-sim
  name: lvm-sci-ag-sim
spec:
  terminationGracePeriodSeconds: 0

  volumes:
  - hostPath:
      path: /lvm
      type: Directory
    name: data-lvm-host-1
  - hostPath:
      path: /lvm/var/data
      type: Directory
    name: data-lvm-host-2
  
  containers:
  - name: lvm-sci-agcam
    image: ghcr.io/sdss/lvmactor:latest
#    image: localhost/lvm_actor:latest
    volumeMounts:
    - mountPath: /root/lvm
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVM_ACTOR
      value: "lvmcam"
    - name: LVM_ACTOR_CONFIG
      value: "lvm.sci.agcam"
    - name: LVM_ACTOR_ARGS
      value: "--rmq_url=amqp://guest:guest@192.168.49.2:5672/ --verbose --simulate"
    - name: LVM_DEBUG
      value: "yes"


  - name: lvm-sci-agp
    image: ghcr.io/sdss/lvmactor:latest
#    image: localhost/lvmactor:latest
    volumeMounts:
    - mountPath: /root/lvm
      name: data-lvm-host-1
    - mountPath: /data
      name: data-lvm-host-2
    env:
    - name: LVM_ACTOR
      value: "lvmagp"
    - name: LVM_ACTOR_CONFIG
      value: "lvm.sci.agp"
    - name: LVM_ACTOR_ARGS
      value: "--rmq_url=amqp://guest:guest@192.168.49.2:5672/ --verbose"
    - name: LVM_DEBUG
      value: "yes"
